services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2_db
      MYSQL_USER: yii2_user
      MYSQL_PASSWORD: yii2_password
    networks:
      my_net:
        ipv4_address: 172.28.0.10
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php_app
    volumes:
      - ./app:/var/www/html
    networks:
      - my_net
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - my_net
    depends_on:
      - php

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - my_net

volumes:
  db_data:

networks:
  my_net:
    ipam:
      config:
        - subnet: 172.28.0.0/16